# Generated by Django 5.0.3 on 2024-03-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
