# Generated by Django 5.0.3 on 2024-03-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_game_date_played"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="date_played",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
