# Generated by Django 5.0.3 on 2024-03-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_game_date_played"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avater",
            new_name="avatar",
        ),
    ]
