services:
  web:
    container_name: django
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    ports:
      - 8000:8000
    command: sh -c "/code/entrypoint.sh"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    
volumes:
  db-data: