services:
  web:
    container_name: django
    build:
      context: .
    command: sh -c "/code/entrypoint.sh"
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      - db
  
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
    
volumes:
  static_volume: